//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class evec_api {
    
    private evec_apiQuicklook quicklookField;
    
    private decimal versionField;
    
    private string methodField;
    
    /// <remarks/>
    public evec_apiQuicklook quicklook {
        get {
            return this.quicklookField;
        }
        set {
            this.quicklookField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiQuicklook {
    
    private byte itemField;
    
    private string itemnameField;
    
    private evec_apiQuicklookRegions regionsField;
    
    private ushort hoursField;
    
    private ushort minqtyField;
    
    private evec_apiQuicklookOrder[] sell_ordersField;
    
    private evec_apiQuicklookOrder1[] buy_ordersField;
    
    /// <remarks/>
    public byte item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string itemname {
        get {
            return this.itemnameField;
        }
        set {
            this.itemnameField = value;
        }
    }
    
    /// <remarks/>
    public evec_apiQuicklookRegions regions {
        get {
            return this.regionsField;
        }
        set {
            this.regionsField = value;
        }
    }
    
    /// <remarks/>
    public ushort hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    public ushort minqty {
        get {
            return this.minqtyField;
        }
        set {
            this.minqtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("order", IsNullable=false)]
    public evec_apiQuicklookOrder[] sell_orders {
        get {
            return this.sell_ordersField;
        }
        set {
            this.sell_ordersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("order", IsNullable=false)]
    public evec_apiQuicklookOrder1[] buy_orders {
        get {
            return this.buy_ordersField;
        }
        set {
            this.buy_ordersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiQuicklookRegions {
    
    private string regionField;
    
    /// <remarks/>
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiQuicklookOrder {
    
    private uint regionField;
    
    private uint stationField;
    
    private string station_nameField;
    
    private decimal securityField;
    
    private ushort rangeField;
    
    private decimal priceField;
    
    private uint vol_remainField;
    
    private byte min_volumeField;
    
    private System.DateTime expiresField;
    
    private string reported_timeField;
    
    private uint idField;
    
    /// <remarks/>
    public uint region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public uint station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    public string station_name {
        get {
            return this.station_nameField;
        }
        set {
            this.station_nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    public ushort range {
        get {
            return this.rangeField;
        }
        set {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public uint vol_remain {
        get {
            return this.vol_remainField;
        }
        set {
            this.vol_remainField = value;
        }
    }
    
    /// <remarks/>
    public byte min_volume {
        get {
            return this.min_volumeField;
        }
        set {
            this.min_volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime expires {
        get {
            return this.expiresField;
        }
        set {
            this.expiresField = value;
        }
    }
    
    /// <remarks/>
    public string reported_time {
        get {
            return this.reported_timeField;
        }
        set {
            this.reported_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiQuicklookOrder1 {
    
    private uint regionField;
    
    private uint stationField;
    
    private string station_nameField;
    
    private decimal securityField;
    
    private short rangeField;
    
    private decimal priceField;
    
    private uint vol_remainField;
    
    private uint min_volumeField;
    
    private System.DateTime expiresField;
    
    private string reported_timeField;
    
    private uint idField;
    
    /// <remarks/>
    public uint region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public uint station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    public string station_name {
        get {
            return this.station_nameField;
        }
        set {
            this.station_nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    public short range {
        get {
            return this.rangeField;
        }
        set {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public uint vol_remain {
        get {
            return this.vol_remainField;
        }
        set {
            this.vol_remainField = value;
        }
    }
    
    /// <remarks/>
    public uint min_volume {
        get {
            return this.min_volumeField;
        }
        set {
            this.min_volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime expires {
        get {
            return this.expiresField;
        }
        set {
            this.expiresField = value;
        }
    }
    
    /// <remarks/>
    public string reported_time {
        get {
            return this.reported_timeField;
        }
        set {
            this.reported_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
