using System;
using System.Net;

namespace eZet.EveLib.Modules.Exceptions {
    public class CrestResourceDeprecatedException : Exception {

        /// <summary>
        /// The response generated by the deprecated resource
        /// </summary>
        public HttpWebResponse Response { get; private set; }

        public CrestResourceDeprecatedException(string message, HttpWebResponse response)
            : base(message) {
            Response = response;
        }
    }
}
