// ***********************************************************************
// Assembly         : EveLib.EveCrest
// Author           : Lars Kristian
// Created          : 12-16-2014
//
// Last Modified By : Lars Kristian
// Last Modified On : 12-17-2014
// ***********************************************************************
// <copyright file="DeprecatedResourceException.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;
using System.Net;

namespace eZet.EveLib.EveCrestModule.Exceptions {
    /// <summary>
    ///     Class DeprecatedResourceException.
    /// </summary>
    public class DeprecatedResourceException : Exception {
        /// <summary>
        ///     Initializes a new instance of the <see cref="DeprecatedResourceException" /> class.
        /// </summary>
        /// <param name="message">The message.</param>
        /// <param name="response">The response.</param>
        public DeprecatedResourceException(string message, HttpWebResponse response)
            : base(message) {
            Response = response;
        }

        /// <summary>
        ///     The response generated by the deprecated resource
        /// </summary>
        /// <value>The response.</value>
        public HttpWebResponse Response { get; private set; }
    }
}