//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class eveapi {
    
    private string currentTimeField;
    
    private eveapiResult resultField;
    
    private string cachedUntilField;
    
    private byte versionField;
    
    /// <remarks/>
    public string currentTime {
        get {
            return this.currentTimeField;
        }
        set {
            this.currentTimeField = value;
        }
    }
    
    /// <remarks/>
    public eveapiResult result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public string cachedUntil {
        get {
            return this.cachedUntilField;
        }
        set {
            this.cachedUntilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eveapiResult {
    
    private eveapiResultTotals totalsField;
    
    private eveapiResultRowset[] rowsetField;
    
    /// <remarks/>
    public eveapiResultTotals totals {
        get {
            return this.totalsField;
        }
        set {
            this.totalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rowset")]
    public eveapiResultRowset[] rowset {
        get {
            return this.rowsetField;
        }
        set {
            this.rowsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eveapiResultTotals {
    
    private ushort killsYesterdayField;
    
    private ushort killsLastWeekField;
    
    private uint killsTotalField;
    
    private ushort victoryPointsYesterdayField;
    
    private uint victoryPointsLastWeekField;
    
    private uint victoryPointsTotalField;
    
    /// <remarks/>
    public ushort killsYesterday {
        get {
            return this.killsYesterdayField;
        }
        set {
            this.killsYesterdayField = value;
        }
    }
    
    /// <remarks/>
    public ushort killsLastWeek {
        get {
            return this.killsLastWeekField;
        }
        set {
            this.killsLastWeekField = value;
        }
    }
    
    /// <remarks/>
    public uint killsTotal {
        get {
            return this.killsTotalField;
        }
        set {
            this.killsTotalField = value;
        }
    }
    
    /// <remarks/>
    public ushort victoryPointsYesterday {
        get {
            return this.victoryPointsYesterdayField;
        }
        set {
            this.victoryPointsYesterdayField = value;
        }
    }
    
    /// <remarks/>
    public uint victoryPointsLastWeek {
        get {
            return this.victoryPointsLastWeekField;
        }
        set {
            this.victoryPointsLastWeekField = value;
        }
    }
    
    /// <remarks/>
    public uint victoryPointsTotal {
        get {
            return this.victoryPointsTotalField;
        }
        set {
            this.victoryPointsTotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eveapiResultRowset {
    
    private eveapiResultRowsetRow[] rowField;
    
    private string nameField;
    
    private string keyField;
    
    private string columnsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("row")]
    public eveapiResultRowsetRow[] row {
        get {
            return this.rowField;
        }
        set {
            this.rowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string columns {
        get {
            return this.columnsField;
        }
        set {
            this.columnsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eveapiResultRowsetRow {
    
    private uint factionIDField;
    
    private string factionNameField;
    
    private ushort pilotsField;
    
    private bool pilotsFieldSpecified;
    
    private byte systemsControlledField;
    
    private bool systemsControlledFieldSpecified;
    
    private byte killsYesterdayField;
    
    private bool killsYesterdayFieldSpecified;
    
    private ushort killsLastWeekField;
    
    private bool killsLastWeekFieldSpecified;
    
    private ushort killsTotalField;
    
    private bool killsTotalFieldSpecified;
    
    private ushort victoryPointsYesterdayField;
    
    private bool victoryPointsYesterdayFieldSpecified;
    
    private ushort victoryPointsLastWeekField;
    
    private bool victoryPointsLastWeekFieldSpecified;
    
    private uint victoryPointsTotalField;
    
    private bool victoryPointsTotalFieldSpecified;
    
    private uint againstIDField;
    
    private bool againstIDFieldSpecified;
    
    private string againstNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint factionID {
        get {
            return this.factionIDField;
        }
        set {
            this.factionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string factionName {
        get {
            return this.factionNameField;
        }
        set {
            this.factionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort pilots {
        get {
            return this.pilotsField;
        }
        set {
            this.pilotsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pilotsSpecified {
        get {
            return this.pilotsFieldSpecified;
        }
        set {
            this.pilotsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte systemsControlled {
        get {
            return this.systemsControlledField;
        }
        set {
            this.systemsControlledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool systemsControlledSpecified {
        get {
            return this.systemsControlledFieldSpecified;
        }
        set {
            this.systemsControlledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte killsYesterday {
        get {
            return this.killsYesterdayField;
        }
        set {
            this.killsYesterdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool killsYesterdaySpecified {
        get {
            return this.killsYesterdayFieldSpecified;
        }
        set {
            this.killsYesterdayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort killsLastWeek {
        get {
            return this.killsLastWeekField;
        }
        set {
            this.killsLastWeekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool killsLastWeekSpecified {
        get {
            return this.killsLastWeekFieldSpecified;
        }
        set {
            this.killsLastWeekFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort killsTotal {
        get {
            return this.killsTotalField;
        }
        set {
            this.killsTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool killsTotalSpecified {
        get {
            return this.killsTotalFieldSpecified;
        }
        set {
            this.killsTotalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort victoryPointsYesterday {
        get {
            return this.victoryPointsYesterdayField;
        }
        set {
            this.victoryPointsYesterdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool victoryPointsYesterdaySpecified {
        get {
            return this.victoryPointsYesterdayFieldSpecified;
        }
        set {
            this.victoryPointsYesterdayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort victoryPointsLastWeek {
        get {
            return this.victoryPointsLastWeekField;
        }
        set {
            this.victoryPointsLastWeekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool victoryPointsLastWeekSpecified {
        get {
            return this.victoryPointsLastWeekFieldSpecified;
        }
        set {
            this.victoryPointsLastWeekFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint victoryPointsTotal {
        get {
            return this.victoryPointsTotalField;
        }
        set {
            this.victoryPointsTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool victoryPointsTotalSpecified {
        get {
            return this.victoryPointsTotalFieldSpecified;
        }
        set {
            this.victoryPointsTotalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint againstID {
        get {
            return this.againstIDField;
        }
        set {
            this.againstIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool againstIDSpecified {
        get {
            return this.againstIDFieldSpecified;
        }
        set {
            this.againstIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string againstName {
        get {
            return this.againstNameField;
        }
        set {
            this.againstNameField = value;
        }
    }
}
