//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace eZet.Eve.EveApi.Dto {


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CharacterSheet {

        public uint characterID { get; set; }

        public string name { get; set; }

        public string DoB { get; set; }

        public string race { get; set; }

        public string bloodLine { get; set; }

        public string ancestry { get; set; }

        public string gender { get; set; }

        public string corporationName { get; set; }

        public uint corporationID { get; set; }

        public object allianceName { get; set; }

        public byte allianceID { get; set; }

        public string cloneName { get; set; }

        public uint cloneSkillPoints { get; set; }

        public decimal balance { get; set; }

        public Implants attributeEnhancers { get; set; }

        public Attributes attributes { get; set; }

        public EveApiRowset<Skill>[] rowset { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class Implants {

        public Implant memoryBonus { get; set; }

        public Implant perceptionBonus { get; set; }

        public Implant willpowerBonus { get; set; }

        public Implant intelligenceBonus { get; set; }

        public Implant charismaBonus { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class Implant {

        public string augmentatorName { get; set; }

        public byte augmentatorValue { get; set; }

    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class Attributes {

        public byte intelligence { get; set; }

        public byte memory { get; set; }

        public byte charisma { get; set; }

        public byte perception { get; set; }

        public byte willpower { get; set; }


    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class Skill {

        [XmlAttribute()]
        public ushort typeID { get; set; }

        [XmlIgnore()]
        public bool typeIDFieldSpecified;

        [XmlAttribute()]
        public uint skillpoints { get; set; }

        [XmlIgnore()]
        public bool skillpointsFieldSpecified;

        [XmlAttribute()]
        public byte level { get; set; }

        [XmlIgnore()]
        public bool levelFieldSpecified;

        [XmlAttribute()]
        public byte published { get; set; }

        [XmlIgnore()]
        public bool publishedFieldSpecified;

        [XmlAttribute()]
        public ushort certificateID { get; set; }

        [XmlIgnore()]
        public bool certificateIDFieldSpecified;

        [XmlAttribute()]
        public byte roleID { get; set; }

        [XmlIgnore()]
        public bool roleIDFieldSpecified;

        [XmlAttribute()]
        public string roleName { get; set; }

        [XmlAttribute()]
        public byte titleID { get; set; }

        [XmlIgnore()]
        public bool titleIDFieldSpecified;

        [XmlAttribute()]
        public string titleName { get; set; }


    }
}