//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace eZet.Eve.EveApi.Dto {

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class TransactionCollection {

        public EveApiRowset<Transaction> rowset { get; set; }

    }

     /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class Transaction {
        [XmlAttribute()]
        public string transactionDateTime { get; set; }

        [XmlAttribute()]
        public uint transactionID { get; set; }
        
        [XmlAttribute()]
        public byte quantity { get; set; }
        
        [XmlAttribute()]
        public string typeName { get; set; }
        
        [XmlAttribute()]
        public ushort typeID { get; set; }
        
        [XmlAttribute()]
        public decimal price { get; set; }
        
        [XmlAttribute()]
        public uint clientID { get; set; }
        
        [XmlAttribute()]
        public string clientName { get; set; }
        
        [XmlAttribute()]
        public uint stationID { get; set; }
        
        [XmlAttribute()]
        public string stationName { get; set; }
        
        [XmlAttribute()]
        public string transactionType { get; set; }
        
        [XmlAttribute()]
        public string transactionFor { get; set; }

    }
}